server.port: 8077
spring:
  application:
    name: trace
  zipkin:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true

monitor:
  url: "localhost:8080"


